extends:
  - stylelint-config-standard
  - stylelint-config-rational-order

plugins:
  - stylelint-order
  - stylelint-config-rational-order/plugin
rules:
  max-line-length: 100
  string-quotes: double
